# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0745e7cbfe73436800c7ccc8913510715a64bafd93c17a064317eddf0d240c82fd9b8b7c4074b4906e27fb23d16d07f9a1e4f2a41a01892f12fb99a66c6523a2

test:
  secret_key_base: 38ca47adb822b1fd83ca488d61f0e0c4da63fe8c54cd532864559409d4a7d2933602cf77882e93bfa295b50854ccf7be42b1513e755b3e27a5d0fca0e1f6367a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
